name: Deploy to AWS Lambda AwaLambdaEmbeddingService

on:
  push:
    branches:
      - main  # mainブランチにpushされたら実行

jobs:
  deploy:
    runs-on: ubuntu-latest  # 実行環境
    
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: AWS CLIをセットアップ
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1  # 東京リージョン（適宜変更）

      - name: JARファイルを作成
        run: |
          # リポジトリのルートに移動
          cd $GITHUB_WORKSPACE
          # binフォルダ内のクラスファイルをJARにまとめる
          jar -cvf AwaLambdaEmbeddingService.jar -C bin .

      - name: Lambda関数をZIP化
        run: |
          zip -r function.zip AwaLambdaEmbeddingService.jar

      - name: Lambdaにデプロイ
        run: |
          aws lambda update-function-code \
            --function-name AwaLambdaEmbeddingService \
            --zip-file fileb://function.zip \
            --region ap-northeast-1

      - name: Lambdaのハンドラを設定
        run: |
          aws lambda update-function-configuration \
            --function-name AwaLambdaEmbeddingService \
            --handler com.ses.handler.LambdaHandler::handleRequest \
            --region ap-northeast-1
